apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  annotations:
    configmanagement.gke.io/namespace-selector: default
  # namespace: default
spec:
  podSelector: {}
  policyTypes:
  - Ingress
