kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: boutique-network-policy
  labels:
    app: frontend
spec:
  policyTypes:
  - Ingress
  # podSelector:
  #   matchLabels:
  #     name: frontend
  ingress:
    - {}
