---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rbac-developer-role-binding
  # namespace: default
subjects:
# Google Cloud user account
- kind: User
  name: oneaniket@gmail.com
  namespace: default
roleRef:
  kind: Role
  name: rbac-developer-role
  apiGroup: rbac.authorization.k8s.io
