---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rbac-developer-role
  # namespace: default
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods","pods/log"]
  verbs: ["get", "watch", "list"]
